### ISSUE TITLE
Principles

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/tb#1]
* no effort is made to avoid confusion resulting from habits or special syntax used in other packages, we start from scratch and challenge everything, but of course keep good ideas.
* [x] What worked (and made sense) on a standard data.frame should work all the same on `tb` objects : https://github.com/moodymudskipper/tb/issues/2
* [x] no assignment by reference : https://github.com/moodymudskipper/tb/issues/3
* [x] `.i` is used only for subsetting (standard subsetting and semi joins) : https://github.com/moodymudskipper/tb/issues/4
* [x] `.j` is used only for selection and transmuting (like `SELECT` in SQL)  
 :https://github.com/moodymudskipper/tb/issues/5 https://github.com/moodymudskipper/tb/issues/8
* [x] `.by` is used only for aggregation (resulting in one row per set of grouping variables) :  https://github.com/moodymudskipper/tb/issues/6
* [x] `...` is used for mutating and summarizing (if `.by` isn't NULL) : https://github.com/moodymudskipper/tb/issues/7 https://github.com/moodymudskipper/tb/issues/8
* [x] A two sided formula notation is used for mutation by group or subsetting by group https://github.com/moodymudskipper/tb/issues/9
* [x] `:=` is used as an extension of `=` which behaves the same whenever `=` works https://github.com/moodymudskipper/tb/issues/10
* [x] `.()` will work as in `bquote()`, not as in *data.table*, for easy substitution https://github.com/moodymudskipper/tb/issues/11
* [x] `.data` can be used anywhere to refer to source table and `.subset` to refer to what is called `.SD` in *data.table*,  https://github.com/moodymudskipper/tb/issues/12
* [ ] All possible data transformations characterized by a main table input should be supported, including pivoting (spread/gather/melt/cast), nesting (nest/unnest/pack/unpack/chop/unchop) and joins, which share the property that they have one main table input. https://github.com/moodymudskipper/tb/issues/13
